# Generated by Django 5.1.15 on 2026-08-14 20:15

import api.rls
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_security_decision_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('review_id', models.UUIDField(db_index=True)),
                ('finding_check_id', models.CharField(blank=True, max_length=200, null=True)),
                ('analyst_id', models.UUIDField(blank=True, null=True)),
                ('analyst_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('decision', models.CharField(max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('rationale_summary', models.TextField(blank=True, null=True)),
                ('provider_type', models.CharField(blank=True, max_length=50, null=True)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'decision_log',
                'ordering': ['-inserted_at'],
                'indexes': [models.Index(fields=['tenant_id', 'inserted_at'], name='dec_log_tenant_time_idx'), models.Index(fields=['tenant_id', 'review_id'], name='dec_log_tenant_review_idx')],
            },
        ),
        migrations.CreateModel(
            name='HITLReviewQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('review_mode', models.CharField(choices=[('standard', 'Standard  -  analyst decides'), ('managed', 'Managed  -  managed service SLA applies'), ('automated', 'Automated  -  system auto-approves below threshold')], default='standard', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, help_text='SLA deadline  -  auto-escalates when crossed in managed mode', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_reviews', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitl_reviews', to='api.finding')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hitl_reviews', to='api.scan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
            options={
                'db_table': 'hitl_review_queue',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagedServiceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=200)),
                ('operator_email', models.EmailField(max_length=254)),
                ('sla_hours', models.IntegerField(default=24, help_text='Maximum hours to resolve a HITL review before escalation')),
                ('escalation_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('max_auto_approve_severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium')], default='low', help_text='Findings at or below this severity may be auto-approved without analyst review', max_length=20)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_service_config', to='api.tenant')),
            ],
            options={
                'db_table': 'managed_service_configs',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approve', 'Approve  -  finding accepted as-is'), ('reject', 'Reject  -  finding disputed or false positive'), ('escalate', 'Escalate  -  needs senior review'), ('request_info', 'Request Info  -  needs more context'), ('mute', 'Mute  -  suppress this finding class')], max_length=20)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes visible only to the managed service team', null=True)),
                ('evidence_links', models.JSONField(blank=True, default=list, help_text='List of URLs or ticket references supporting this decision')),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('analyst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_decisions', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='api.hitlreviewqueue')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
            options={
                'db_table': 'review_decisions',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='hitlreviewqueue',
            index=models.Index(fields=['tenant_id', 'status'], name='hitl_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hitlreviewqueue',
            index=models.Index(fields=['tenant_id', 'due_at'], name='hitl_tenant_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='hitlreviewqueue',
            constraint=api.rls.RowLevelSecurityConstraint('tenant_id', name='rls_on_hitlreviewqueue'),
        ),
        migrations.AddConstraint(
            model_name='managedserviceconfig',
            constraint=api.rls.RowLevelSecurityConstraint('tenant_id', name='rls_on_managedserviceconfig'),
        ),
        migrations.AddIndex(
            model_name='reviewdecision',
            index=models.Index(fields=['tenant_id', 'inserted_at'], name='review_dec_tenant_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewdecision',
            constraint=api.rls.RowLevelSecurityConstraint('tenant_id', name='rls_on_reviewdecision'),
        ),
    ]
