# Generated by Django 5.1.15 on 2026-08-15 07:13

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_decisionlog_hitlreviewqueue_managedserviceconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CISOAdvisorConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('referenced_findings', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=1.0)),
                ('model_name', models.CharField(default='qwen-3.5-9b', max_length=200)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciso_conversations', to='api.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ciso_advisor_conversations',
                'ordering': ['-inserted_at'],
            },
        ),
        migrations.CreateModel(
            name='RemediationPlaybook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('script_type', models.CharField(choices=[('terraform', 'Terraform HCL'), ('aws_cli', 'AWS CLI Script'), ('azure_cli', 'Azure CLI Script'), ('gcloud_cli', 'Google Cloud CLI'), ('powershell', 'PowerShell Script'), ('python', 'Python Boto3 / Azure SDK'), ('ansible', 'Ansible Playbook')], default='terraform', max_length=50)),
                ('code_snippet', models.TextField()),
                ('rollback_snippet', models.TextField(blank=True, null=True)),
                ('estimated_downtime_minutes', models.IntegerField(default=0)),
                ('requires_maintenance_window', models.BooleanField(default=False)),
                ('is_automated', models.BooleanField(default=False)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_playbooks', to='api.tenant')),
            ],
            options={
                'db_table': 'remediation_playbooks',
                'ordering': ['-inserted_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantLLMConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Primary Azure vLLM (Qwen)', max_length=150)),
                ('provider_type', models.CharField(choices=[('vllm_azure', 'vLLM (Azure VM)'), ('azure_openai', 'Azure OpenAI'), ('anthropic_claude', 'Anthropic Claude'), ('ollama', 'Ollama / Local')], default='vllm_azure', max_length=50)),
                ('base_url', models.CharField(default='http://localhost:8000/v1', help_text='vLLM OpenAI-compatible endpoint URL (e.g., http://<azure-vm-ip>:8000/v1)', max_length=500)),
                ('model_name', models.CharField(default='qwen-3.5-9b', help_text='Model identifier served by vLLM (e.g., qwen-3.5-9b, Qwen/Qwen2.5-7B-Instruct)', max_length=200)),
                ('api_key', models.CharField(blank=True, default='EMPTY', max_length=500)),
                ('temperature', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=3)),
                ('max_tokens', models.IntegerField(default=4096)),
                ('is_active', models.BooleanField(default=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to='api.tenant')),
            ],
            options={
                'db_table': 'tenant_llm_configs',
                'ordering': ['-inserted_at'],
            },
        ),
        migrations.CreateModel(
            name='FindingAIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_id', models.UUIDField(db_index=True)),
                ('finding_hash', models.CharField(db_index=True, max_length=64)),
                ('check_id', models.CharField(blank=True, max_length=200, null=True)),
                ('resource_uid', models.CharField(blank=True, max_length=500, null=True)),
                ('summary', models.TextField()),
                ('domain', models.CharField(default='General Security', max_length=100)),
                ('exposure', models.CharField(default='Internal', max_length=50)),
                ('root_cause', models.TextField()),
                ('technical_impact', models.TextField()),
                ('business_impact', models.TextField()),
                ('attack_scenario', models.TextField()),
                ('remediation_steps', models.JSONField(default=list)),
                ('verification_steps', models.JSONField(default=list)),
                ('unknowns', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.9)),
                ('model_name', models.CharField(default='qwen-3.5-9b', max_length=200)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='api.tenant')),
            ],
            options={
                'db_table': 'finding_ai_analyses',
                'ordering': ['-inserted_at'],
                'indexes': [models.Index(fields=['tenant', 'finding_hash'], name='ai_analysis_hash_idx'), models.Index(fields=['tenant', 'finding_id'], name='ai_analysis_finding_idx')],
            },
        ),
    ]
