# Generated by Django 5.1.15 on 2026-08-16 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_digital_ciso_vllm_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediationplaybook',
            name='approval_status',
            field=models.CharField(choices=[('pending_approval', 'Pending Human Approval'), ('approved', 'Approved by Admin'), ('rejected', 'Rejected by Admin'), ('executing', 'Executing'), ('executed_success', 'Executed Successfully'), ('executed_failed', 'Execution Failed')], default='pending_approval', max_length=50),
        ),
        migrations.AddField(
            model_name='remediationplaybook',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remediationplaybook',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_playbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remediationplaybook',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remediationplaybook',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_playbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remediationplaybook',
            name='execution_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remediationplaybook',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
