# Generated by Django 5.1.15 on 2026-08-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_hitl_remediation_execution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydecision',
            name='jira_ticket_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='securitydecision',
            name='jira_ticket_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
