# Generated by Django 5.1.15 on 2026-08-20 12:10

import api.rls
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0105_oracle_saas_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemediationExecution",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("finding_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("issue_key", models.CharField(db_index=True, max_length=50)),
                ("issue_url", models.URLField(blank=True, max_length=500, null=True)),
                ("issue_id", models.CharField(blank=True, max_length=50, null=True)),
                ("project_key", models.CharField(max_length=50)),
                ("summary", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.CharField(choices=[("PENDING", "Pending Ticket Creation"), ("IN_PROGRESS", "In Progress (Jira Active)"), ("COMPLETED", "Completed (Jira Resolved)"), ("FAILED", "Failed")], db_index=True, default="PENDING", max_length=50)),
                ("jira_status", models.CharField(default="To Do", max_length=100)),
                ("jira_status_category", models.CharField(default="new", max_length=50)),
                ("priority", models.CharField(default="Medium", max_length=50)),
                ("assignee_name", models.CharField(blank=True, max_length=200, null=True)),
                ("assignee_email", models.CharField(blank=True, max_length=200, null=True)),
                ("assignee_account_id", models.CharField(blank=True, max_length=200, null=True)),
                ("labels", models.JSONField(blank=True, default=list)),
                ("ai_payload", models.JSONField(blank=True, default=dict)),
                ("timeline", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("decision", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="remediation_executions", to="api.securitydecision")),
                ("playbook", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="remediation_executions", to="api.remediationplaybook")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="remediation_executions", to="api.tenant")),
            ],
            options={
                "db_table": "remediation_executions",
                "ordering": ["-inserted_at"],
            },
        ),
        migrations.CreateModel(
            name="JiraProjectMapping",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("project_key", models.CharField(max_length=50)),
                ("project_name", models.CharField(max_length=200)),
                ("default_issue_type", models.CharField(default="Task", max_length=100)),
                ("default_priority", models.CharField(default="Medium", max_length=50)),
                ("default_assignee_account_id", models.CharField(blank=True, max_length=200, null=True)),
                ("default_assignee_name", models.CharField(blank=True, max_length=200, null=True)),
                ("default_labels", models.JSONField(blank=True, default=list)),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jira_project_mappings", to="api.tenant")),
            ],
            options={
                "db_table": "jira_project_mappings",
                "unique_together": {("tenant", "project_key")},
            },
        ),
        migrations.CreateModel(
            name="JiraAssigneeCache",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("project_key", models.CharField(db_index=True, max_length=50)),
                ("account_id", models.CharField(db_index=True, max_length=200)),
                ("display_name", models.CharField(max_length=200)),
                ("email_address", models.CharField(blank=True, max_length=200, null=True)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jira_assignees_cache", to="api.tenant")),
            ],
            options={
                "db_table": "jira_assignees_cache",
                "unique_together": {("tenant", "project_key", "account_id")},
            },
        ),
        migrations.AddIndex(
            model_name="remediationexecution",
            index=models.Index(fields=["tenant_id", "status"], name="remed_exec_tenant_status_idx"),
        ),
        migrations.AddIndex(
            model_name="remediationexecution",
            index=models.Index(fields=["tenant_id", "issue_key"], name="remed_exec_tenant_key_idx"),
        ),
        migrations.AddIndex(
            model_name="remediationexecution",
            index=models.Index(fields=["tenant_id", "finding_id"], name="remed_exec_tenant_find_idx"),
        ),
    ]
