# Generated by Django 5.1.15 on 2026-09-29 15:33

import api.db_utils
import api.rls
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_jira_remediation_execution_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('add_cloud', 'Add Cloud Provider'), ('remove_cloud', 'Remove Cloud Provider'), ('add_compliance', 'Add Compliance Framework'), ('remove_compliance', 'Remove Compliance Framework')], max_length=30)),
                ('target_value', models.CharField(max_length=200)),
                ('target_display_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'subscription_change_requests',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantCloudSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', api.db_utils.ProviderEnumField(choices=[('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('kubernetes', 'Kubernetes'), ('m365', 'M365'), ('github', 'GitHub'), ('mongodbatlas', 'MongoDB Atlas'), ('iac', 'IaC'), ('oraclecloud', 'Oracle Cloud Infrastructure'), ('alibabacloud', 'Alibaba Cloud'), ('cloudflare', 'Cloudflare'), ('openstack', 'OpenStack'), ('image', 'Image'), ('googleworkspace', 'Google Workspace'), ('vercel', 'Vercel'), ('okta', 'Okta'), ('oracle_saas', 'Oracle SaaS / ERP')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tenant_cloud_subscriptions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantComplianceSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework_id', models.CharField(max_length=150)),
                ('framework_name', models.CharField(blank=True, max_length=200)),
                ('provider_type', api.db_utils.ProviderEnumField(blank=True, choices=[('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('kubernetes', 'Kubernetes'), ('m365', 'M365'), ('github', 'GitHub'), ('mongodbatlas', 'MongoDB Atlas'), ('iac', 'IaC'), ('oraclecloud', 'Oracle Cloud Infrastructure'), ('alibabacloud', 'Alibaba Cloud'), ('cloudflare', 'Cloudflare'), ('openstack', 'OpenStack'), ('image', 'Image'), ('googleworkspace', 'Google Workspace'), ('vercel', 'Vercel'), ('okta', 'Okta'), ('oracle_saas', 'Oracle SaaS / ERP')], null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tenant_compliance_subscriptions',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='jiraassigneecache',
            constraint=api.rls.RowLevelSecurityConstraint('tenant_id', name='rls_on_jiraassigneecache'),
        ),
        migrations.AddConstraint(
            model_name='jiraprojectmapping',
            constraint=api.rls.RowLevelSecurityConstraint('tenant_id', name='rls_on_jiraprojectmapping'),
        ),
        migrations.AddConstraint(
            model_name='remediationexecution',
            constraint=api.rls.RowLevelSecurityConstraint('tenant_id', name='rls_on_remediationexecution'),
        ),
        migrations.AddField(
            model_name='subscriptionchangerequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionchangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_subscription_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionchangerequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
        ),
        migrations.AddField(
            model_name='tenantcloudsubscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
        ),
        migrations.AddField(
            model_name='tenantcompliancesubscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionchangerequest',
            constraint=api.rls.RowLevelSecurityConstraint('tenant_id', name='rls_on_subscriptionchangerequest'),
        ),
        migrations.AddConstraint(
            model_name='tenantcloudsubscription',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider_type'), name='unique_tenant_cloud_subscription'),
        ),
        migrations.AddConstraint(
            model_name='tenantcloudsubscription',
            constraint=api.rls.RowLevelSecurityConstraint('tenant_id', name='rls_on_tenantcloudsubscription'),
        ),
        migrations.AddConstraint(
            model_name='tenantcompliancesubscription',
            constraint=models.UniqueConstraint(fields=('tenant', 'framework_id'), name='unique_tenant_compliance_subscription'),
        ),
        migrations.AddConstraint(
            model_name='tenantcompliancesubscription',
            constraint=api.rls.RowLevelSecurityConstraint('tenant_id', name='rls_on_tenantcompliancesubscription'),
        ),
    ]
