/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttackPathsRouteImport } from './routes/attack-paths'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ScansRouteImport } from './routes/scans'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as UsersRouteImport } from './routes/users'
import { Route as AiAdvisorRouteImport } from './routes/ai.advisor'
import { Route as AiDecisionsRouteImport } from './routes/ai.decisions'
import { Route as AiSettingsRouteImport } from './routes/ai.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttackPathsRoute = AttackPathsRouteImport.update({
  id: '/attack-paths',
  path: '/attack-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansRoute = ScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAdvisorRoute = AiAdvisorRouteImport.update({
  id: '/ai/advisor',
  path: '/ai/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDecisionsRoute = AiDecisionsRouteImport.update({
  id: '/ai/decisions',
  path: '/ai/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSettingsRoute = AiSettingsRouteImport.update({
  id: '/ai/settings',
  path: '/ai/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attack-paths': typeof AttackPathsRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/findings': typeof FindingsRoute
  '/integrations': typeof IntegrationsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/scans': typeof ScansRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/users': typeof UsersRoute
  '/ai/advisor': typeof AiAdvisorRoute
  '/ai/decisions': typeof AiDecisionsRoute
  '/ai/settings': typeof AiSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attack-paths': typeof AttackPathsRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/findings': typeof FindingsRoute
  '/integrations': typeof IntegrationsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/scans': typeof ScansRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/users': typeof UsersRoute
  '/ai/advisor': typeof AiAdvisorRoute
  '/ai/decisions': typeof AiDecisionsRoute
  '/ai/settings': typeof AiSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attack-paths': typeof AttackPathsRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/findings': typeof FindingsRoute
  '/integrations': typeof IntegrationsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/scans': typeof ScansRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/users': typeof UsersRoute
  '/ai/advisor': typeof AiAdvisorRoute
  '/ai/decisions': typeof AiDecisionsRoute
  '/ai/settings': typeof AiSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attack-paths'
    | '/compliance'
    | '/dashboard'
    | '/findings'
    | '/integrations'
    | '/profile'
    | '/providers'
    | '/reports'
    | '/resources'
    | '/scans'
    | '/sign-in'
    | '/sign-up'
    | '/users'
    | '/ai/advisor'
    | '/ai/decisions'
    | '/ai/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attack-paths'
    | '/compliance'
    | '/dashboard'
    | '/findings'
    | '/integrations'
    | '/profile'
    | '/providers'
    | '/reports'
    | '/resources'
    | '/scans'
    | '/sign-in'
    | '/sign-up'
    | '/users'
    | '/ai/advisor'
    | '/ai/decisions'
    | '/ai/settings'
  id:
    | '__root__'
    | '/'
    | '/attack-paths'
    | '/compliance'
    | '/dashboard'
    | '/findings'
    | '/integrations'
    | '/profile'
    | '/providers'
    | '/reports'
    | '/resources'
    | '/scans'
    | '/sign-in'
    | '/sign-up'
    | '/users'
    | '/ai/advisor'
    | '/ai/decisions'
    | '/ai/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttackPathsRoute: typeof AttackPathsRoute
  ComplianceRoute: typeof ComplianceRoute
  DashboardRoute: typeof DashboardRoute
  FindingsRoute: typeof FindingsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  ProfileRoute: typeof ProfileRoute
  ProvidersRoute: typeof ProvidersRoute
  ReportsRoute: typeof ReportsRoute
  ResourcesRoute: typeof ResourcesRoute
  ScansRoute: typeof ScansRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UsersRoute: typeof UsersRoute
  AiAdvisorRoute: typeof AiAdvisorRoute
  AiDecisionsRoute: typeof AiDecisionsRoute
  AiSettingsRoute: typeof AiSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attack-paths': {
      id: '/attack-paths'
      path: '/attack-paths'
      fullPath: '/attack-paths'
      preLoaderRoute: typeof AttackPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans': {
      id: '/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/advisor': {
      id: '/ai/advisor'
      path: '/ai/advisor'
      fullPath: '/ai/advisor'
      preLoaderRoute: typeof AiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/decisions': {
      id: '/ai/decisions'
      path: '/ai/decisions'
      fullPath: '/ai/decisions'
      preLoaderRoute: typeof AiDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/settings': {
      id: '/ai/settings'
      path: '/ai/settings'
      fullPath: '/ai/settings'
      preLoaderRoute: typeof AiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttackPathsRoute: AttackPathsRoute,
  ComplianceRoute: ComplianceRoute,
  DashboardRoute: DashboardRoute,
  FindingsRoute: FindingsRoute,
  IntegrationsRoute: IntegrationsRoute,
  ProfileRoute: ProfileRoute,
  ProvidersRoute: ProvidersRoute,
  ReportsRoute: ReportsRoute,
  ResourcesRoute: ResourcesRoute,
  ScansRoute: ScansRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UsersRoute: UsersRoute,
  AiAdvisorRoute: AiAdvisorRoute,
  AiDecisionsRoute: AiDecisionsRoute,
  AiSettingsRoute: AiSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
